version: '3.4'

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "9999:80/tcp"
  
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8888:80/tcp"
        
  db:
    ports:
      - "1433:1433/tcp"